using Masterov.Domain.Masterov.FinishedProduct.GetFinishedProductsByUpdatedAtWithoutOrders.Query;
using Masterov.Domain.Models;

namespace Masterov.Domain.Masterov.FinishedProduct.GetFinishedProductsByUpdatedAtWithoutOrders;

public interface IGetFinishedProductsByUpdatedAtWithoutOrdersUseCase
{
    Task<IEnumerable<FinishedProductNoOrdersDomain>?> Execute(GetFinishedProductsByUpdatedAtWithoutOrdersQuery getFinishedProductsByUpdatedAtQuery, CancellationToken cancellationToken);
}